M48
; DRILL file {KiCad 7.0.8} date 2023 November 23, Thursday 11:52:29
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-23T11:52:29-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X9.5031Y-13.8516
X9.5031Y-13.95
X9.7Y-13.6547
X9.8969Y-13.8516
X9.8969Y-13.95
T2
X8.5Y-5.65
X8.5Y-13.9
X14.6Y-13.9
X14.65Y-5.65
T0
M30
